# This is a placeholder for Alembic migration scripts.
# In a real project, you would use `alembic init` and `alembic revision -m "message"`
# to generate migration files.
# This file represents the initial schema based on the provided models.

"""
Initial database schema migration.

Revision ID: 001
Revises: 
Create Date: 2023-10-27 10:00:00.000000
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users', 
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('email', sa.VARCHAR(length=255), nullable=False), 
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=True), 
    sa.Column('google_id', sa.VARCHAR(length=255), nullable=True), 
    sa.Column('display_name', sa.VARCHAR(length=100), nullable=False), 
    sa.Column('avatar_url', sa.VARCHAR(length=255), nullable=True), 
    sa.Column('role', sa.VARCHAR(length=50), nullable=False), 
    sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True), 
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False), 
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), onupdate=sa.text('NOW()'), nullable=False), 
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=False)
    op.create_foreign_key('fk_users_parent_id_users', 'users', 'users', ['parent_id'], ['user_id'])
    
    op.create_table('family_members', 
    sa.Column('family_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('member_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('role_in_family', sa.VARCHAR(length=50), nullable=False)
    )
    op.create_primary_key('pk_family_members', 'family_members', ['family_id', 'member_id'])
    op.create_index('ix_family_members_family_id', 'family_members', ['family_id'], unique=False)
    op.create_foreign_key('fk_family_members_member_id_users', 'family_members', 'users', ['member_id'], ['user_id'])
    
    op.create_table('event_categories', 
    sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('family_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('name', sa.VARCHAR(length=100), nullable=False), 
    sa.Column('color', sa.VARCHAR(length=7), nullable=False)
    )
    op.create_primary_key('pk_event_categories', 'event_categories', ['category_id'])
    op.create_index('ix_event_categories_family_id', 'event_categories', ['family_id'], unique=False)
    op.create_foreign_key('fk_event_categories_family_id_family_members', 'event_categories', 'family_members', ['family_id'], ['family_id'])
    
    op.create_table('events', 
    sa.Column('event_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('family_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('title', sa.VARCHAR(length=255), nullable=False), 
    sa.Column('description', sa.TEXT(), nullable=True), 
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False), 
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=False), 
    sa.Column('assigned_to', postgresql.UUID(as_uuid=True), nullable=True), 
    sa.Column('event_category_id', postgresql.UUID(as_uuid=True), nullable=True), 
    sa.Column('location', sa.VARCHAR(length=255), nullable=True), 
    sa.Column('is_recurring', sa.BOOLEAN(), server_default=sa.text('False'), nullable=True), 
    sa.Column('recurrence_rule', sa.TEXT(), nullable=True), 
    sa.Column('recurring_end_date', sa.TIMESTAMP(timezone=True), nullable=True), 
    sa.Column('original_event_id', postgresql.UUID(as_uuid=True), nullable=True), 
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False), 
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), onupdate=sa.text('NOW()'), nullable=False)
    )
    op.create_primary_key('pk_events', 'events', ['event_id'])
    op.create_index('ix_events_event_id', 'events', ['event_id'], unique=False)
    op.create_foreign_key('fk_events_family_id_family_members', 'events', 'family_members', ['family_id'], ['family_id'])
    op.create_foreign_key('fk_events_assigned_to_users', 'events', 'users', ['assigned_to'], ['user_id'])
    op.create_foreign_key('fk_events_event_category_id_event_categories', 'events', 'event_categories', ['event_category_id'], ['category_id'])
    op.create_foreign_key('fk_events_original_event_id_events', 'events', 'events', ['original_event_id'], ['event_id'])
    op.create_foreign_key('fk_events_created_by_users', 'events', 'users', ['created_by'], ['user_id'])
    
    op.create_table('tasks', 
    sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('family_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('title', sa.VARCHAR(length=255), nullable=False), 
    sa.Column('description', sa.TEXT(), nullable=True), 
    sa.Column('assigned_to', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('due_date', sa.TIMESTAMP(timezone=True), nullable=True), 
    sa.Column('points', sa.INTEGER(), server_default=sa.text('0'), nullable=False), 
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text('pending'), nullable=False), 
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False), 
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), onupdate=sa.text('NOW()'), nullable=False)
    )
    op.create_primary_key('pk_tasks', 'tasks', ['task_id'])
    op.create_index('ix_tasks_task_id', 'tasks', ['task_id'], unique=False)
    op.create_foreign_key('fk_tasks_family_id_family_members', 'tasks', 'family_members', ['family_id'], ['family_id'])
    op.create_foreign_key('fk_tasks_assigned_to_users', 'tasks', 'users', ['assigned_to'], ['user_id'])
    op.create_foreign_key('fk_tasks_created_by_users', 'tasks', 'users', ['created_by'], ['user_id'])
    
    op.create_table('rewards', 
    sa.Column('reward_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('family_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('name', sa.VARCHAR(length=100), nullable=False), 
    sa.Column('description', sa.TEXT(), nullable=True), 
    sa.Column('point_cost', sa.INTEGER(), server_default=sa.text('0'), nullable=False), 
    sa.Column('requires_approval', sa.BOOLEAN(), server_default=sa.text('False'), nullable=True), 
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False), 
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), onupdate=sa.text('NOW()'), nullable=False)
    )
    op.create_primary_key('pk_rewards', 'rewards', ['reward_id'])
    op.create_index('ix_rewards_reward_id', 'rewards', ['reward_id'], unique=False)
    op.create_foreign_key('fk_rewards_family_id_family_members', 'rewards', 'family_members', ['family_id'], ['family_id'])
    op.create_foreign_key('fk_rewards_created_by_users', 'rewards', 'users', ['created_by'], ['user_id'])
    
    op.create_table('reward_redemptions', 
    sa.Column('redemption_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('reward_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('redeemed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False), 
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text('pending'), nullable=False), 
    sa.Column('approved_by', postgresql.UUID(as_uuid=True), nullable=True), 
    sa.Column('approved_at', sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.create_primary_key('pk_reward_redemptions', 'reward_redemptions', ['redemption_id'])
    op.create_index('ix_reward_redemptions_redemption_id', 'reward_redemptions', ['redemption_id'], unique=False)
    op.create_foreign_key('fk_reward_redemptions_reward_id_rewards', 'reward_redemptions', 'rewards', ['reward_id'], ['reward_id'])
    op.create_foreign_key('fk_reward_redemptions_user_id_users', 'reward_redemptions', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key('fk_reward_redemptions_approved_by_users', 'reward_redemptions', 'users', ['approved_by'], ['user_id'])
    
    op.create_table('user_points', 
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('current_points', sa.INTEGER(), server_default=sa.text('0'), nullable=False)
    )
    op.create_primary_key('pk_user_points', 'user_points', ['user_id'])
    op.create_foreign_key('fk_user_points_user_id_users', 'user_points', 'users', ['user_id'], ['user_id'])
    
    op.create_table('notifications', 
    sa.Column('notification_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('message', sa.TEXT(), nullable=False), 
    sa.Column('type', sa.VARCHAR(length=50), nullable=False), 
    sa.Column('read_status', sa.BOOLEAN(), server_default=sa.text('False'), nullable=True), 
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False)
    )
    op.create_primary_key('pk_notifications', 'notifications', ['notification_id'])
    op.create_index('ix_notifications_notification_id', 'notifications', ['notification_id'], unique=False)
    op.create_foreign_key('fk_notifications_user_id_users', 'notifications', 'users', ['user_id'], ['user_id'])
    
    op.create_table('subscriptions', 
    sa.Column('subscription_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('plan_name', sa.VARCHAR(length=100), nullable=False), 
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False), 
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=True), 
    sa.Column('status', sa.VARCHAR(50), server_default=sa.text('active'), nullable=False), 
    sa.Column('payment_gateway_subscription_id', sa.VARCHAR(length=255), nullable=True)
    )
    op.create_primary_key('pk_subscriptions', 'subscriptions', ['subscription_id'])
    op.create_index('ix_subscriptions_subscription_id', 'subscriptions', ['subscription_id'], unique=False)
    op.create_foreign_key('fk_subscriptions_user_id_users', 'subscriptions', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('notifications')
    op.drop_table('user_points')
    op.drop_table('reward_redemptions')
    op.drop_table('rewards')
    op.drop_table('tasks')
    op.drop_table('events')
    op.drop_table('event_categories')
    op.drop_table('family_members')
    op.drop_table('users')
    # ### end Alembic commands ###
